# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install system library dependencies
        run: |
          sudo apt update
          sudo apt install -y libgl1-mesa-dev libegl1-mesa-dev xorg-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-xinerama0-dev libxcb-util-dev uuid-dev gcc-8 g++-8 gfortran-8
          
      - name: Install Conan
        run: |
          pip3 install wheel setuptools
          pip3 install conan
          
      - name: Setup C++ toolchain
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100 --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8
          conan profile new --detect default
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan profile update conf.tools.system.package_manager:mode=install default
          conan profile update conf.tools.system.package_manager:sudo=True default
          
      - name: Add Conan remote
        run: |
          conan remote add bincrafters https://bincrafters.jfrog.io/artifactory/api/conan/public-conan
          conan config set general.revisions_enabled=1
          conan remote add oppen-public https://oppentech.jfrog.io/artifactory/api/conan/public
          
      - name: Create build directory
        run: |
          mkdir ${{github.workspace}}/build
          mkdir ${{github.workspace}}/utils_build
          mkdir ${{github.workspace}}/demos_build
          
      - name: Build eustis
        working-directory: ${{github.workspace}}/build
        run: |
          conan install .. -b missing
